-- MySQL Script generated by MySQL Workbench
-- Mon May  4 15:17:51 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco` DEFAULT CHARACTER SET utf8 ;
USE `banco` ;

-- -----------------------------------------------------
-- Table `banco`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_nome` VARCHAR(255) NOT NULL,
  `usuario_senha` VARCHAR(255) NOT NULL,
  `usuario_tipo` CHAR(1) NOT NULL DEFAULT 'a',
  `usuario_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`usuario_id`),
  UNIQUE INDEX `usuario_email_UNIQUE` (`usuario_email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`ponto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`ponto` (
  `ponto_id` INT NOT NULL AUTO_INCREMENT,
  `ponto_nome` VARCHAR(255) NOT NULL,
  `ponto_descricao` VARCHAR(255) NULL,
  `ponto_horario` VARCHAR(45) NULL,
  PRIMARY KEY (`ponto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`aluno` (
  `aluno_id` INT NOT NULL AUTO_INCREMENT,
  `aluno_nome` VARCHAR(255) NOT NULL,
  `aluno_cpf` VARCHAR(14) NOT NULL,
  `aluno_telefone` VARCHAR(45) NOT NULL,
  `aluno_endereco` VARCHAR(45) NOT NULL,
  `aluno_data_nasc` DATE NOT NULL,
  `aluno_status` CHAR(8) NULL DEFAULT 'ativo',
  `ponto_ponto_id` INT NOT NULL,
  `aluno_foto` VARCHAR(255) NULL,
  `aluno_serie` VARCHAR(45) NOT NULL,
  `aluno_responsavel` VARCHAR(255) NOT NULL,
  `aluno_responsavel_telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`aluno_id`),
  UNIQUE INDEX `aluno_cpf_UNIQUE` (`aluno_cpf` ASC) VISIBLE,
  INDEX `fk_aluno_ponto_idx` (`ponto_ponto_id` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_ponto`
    FOREIGN KEY (`ponto_ponto_id`)
    REFERENCES `banco`.`ponto` (`ponto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`pagamento` (
  `pagamento_id` INT NOT NULL AUTO_INCREMENT,
  `pagamento_mes` VARCHAR(54) NOT NULL,
  `pagamento_data` DATE NOT NULL,
  `pagamento_valor` DECIMAL(10,2) NOT NULL,
  `pagamento_status` ENUM('pago', 'pendente', 'atrasado') NOT NULL DEFAULT 'pendente',
  `pagamento_comprovante` VARCHAR(255) NULL,
  `pagamento_tipo` ENUM('pix', 'dinheiro', 'nao_definido') NOT NULL DEFAULT 'nao_definido',
  `aluno_aluno_id` INT NOT NULL,
  PRIMARY KEY (`pagamento_id`),
  INDEX `fk_pagamento_aluno1_idx` (`aluno_aluno_id` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_aluno1`
    FOREIGN KEY (`aluno_aluno_id`)
    REFERENCES `banco`.`aluno` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`recibo` (
  `recibo_id` INT NOT NULL AUTO_INCREMENT,
  `recibo_aluno_id` INT NOT NULL,
  `recibo_descricao` VARCHAR(255) NULL,
  `pagamento_pagamento_id` INT NOT NULL,
  PRIMARY KEY (`recibo_id`),
  INDEX `fk_recibo_aluno1_idx` (`recibo_aluno_id` ASC) VISIBLE,
  INDEX `fk_recibo_pagamento1_idx` (`pagamento_pagamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_recibo_aluno1`
    FOREIGN KEY (`recibo_aluno_id`)
    REFERENCES `banco`.`aluno` (`aluno_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recibo_pagamento1`
    FOREIGN KEY (`pagamento_pagamento_id`)
    REFERENCES `banco`.`pagamento` (`pagamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
